### ISSUE TITLE
Streaming-Gateway error in high rate

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1367]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
API-gateway error in high rate 
when sending more than 20 messages/sec   the sender  received the following error:
```
UnhandledPromiseRejectionWarning: Error: Request failed with status code 502
    at createError (/home/tamirre/Documents/test/system-test-node/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/tamirre/Documents/test/system-test-node/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/tamirre/Documents/test/system-test-node/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
when receiving this error some of the stateless workers issued the following errors:

- unhandledRejection: Cannot read property 'data' of null

- Cannot read property 'scale' of null

- Cannot read property 'metrics' of null

the pipeline

```json
{
    "name": "raw-gateway-test",
    "kind": "stream",
    "nodes": [
        {
            "nodeName": "A",
            "kind": "gateway",
            "spec": {
                "name": "raw-image-gateway",
                "description": "images streaming source",
                "cpu": 1,
                "mem": "1Gi"
            },
            "input": [],
            "stateType": "stateful"
        },
        {
            "nodeName": "B",
            "algorithmName": "green-alg",
            "input": [
                {
                    "delay": 0.01
                }
            ],
            "kind": "algorithm",
            "stateType": "stateless"
        }
    ],
    "streaming": {
        "flows": {
            "analyze": "A >> B"
        }
    },
    "experimentName": "main",
    "options": {
        "ttl": 3600,
        "batchTolerance": 80,
        "progressVerbosityLevel": "info"
    },
    "priority": 3
}

**Expected behavior**
A clear and concise description of what you expected to happen.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by tamir321** [comment]
tested on
systemVersion: "v2.1.88",
fullSystemVersion: "v2.1.88-1631616917808",
