### ISSUE TITLE
Rebuild failed Error: unable to find build ->...

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1412]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
Rebuild failed Error: unable to find build ->...

**To Reproduce**
build algorithim 
wait a day for ETCD to be deleted
try to rebuild the algorithm 
"Error: unable to find build -> get-twitt-a-jxbqls at _watchBuild (/hkube/algorithm-builder/lib/builds/docker-builder.js:173:15) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async Object.runBuild (/hkube/algorithm-builder/lib/builds/docker-builder.js:475:17) at async Bootstrap.init (/hkube/algorithm-builder/bootstrap.js:23:30)"
 

**Screenshots**

**Additional context**

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.2.45",
fullSystemVersion: "v2.2.45-1645610255014",
