### ISSUE TITLE
in debug  "hkubeapi.start_algorithm" and "start_stored_subpipeline" with "resultAsRaw=True" does not return results

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#830]
**HKube micro-service**
code api

**Describe the bug**
when debugging Pthon algorithm  "hkubeapi.start_algorithm" and "start_stored_subpipeline" with "resultAsRaw=True" does not return results (if building  the algorithm it works properly  )

code example

```python

import time
def start(args, hkubeapi):
    input=args['input'][0]
    if input and input["action"] == "start_alg":
        ret = hkubeapi.start_algorithm(input["name"], input["input"], resultAsRaw=True, blocking=True) #input["resultAsRaw"]
        time.sleep(2)    
        print(ret)
        return ret
   
    if input and input["action"] == "start_stored_subpipeline":
        ret = hkubeapi.start_stored_subpipeline(input["name"], input["input"],  blocking=True)
        time.sleep(2)    
        print(ret)
        return ret
    time.sleep(1)
    return "did not get response"

**Comment by tamir321** [comment]
to start algorithm use 
```json
{
    "action":"start_alg",
    "name":"yellow-alg",
    "input":[7]
    
    }

```
to start sub pipeline use
```json
{
    "action":"start_stored_subpipeline",
    "name":"simple",
    "input":{"inp":7}  
    }

**Comment by tamir321** [comment]
on  "systemVersion": "v1.3.46",
    "fullSystemVersion": "v1.3.46-1593064528107",
    "versions": [

connected to ws://test.hkube.io/hkube/debug/tamir?storage=v2&encoding=bson
got message from worker: initialize
sending message to worker: initialized
got message from worker: start
sending message to worker: started
start_algorithm called with yellow-alg
sending message to worker: startAlgorithmExecution
got message from worker: algorithmExecutionDone
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/tamirre/envs/python36/lib/python3.6/site-packages/hkube_python_wrapper/wrapper/wc.py", line 49, in algorithmExecutionDone
    self.events.on_algorithmExecutionDone(data)
  File "/home/tamirre/envs/python36/lib/python3.6/site-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/tamirre/envs/python36/lib/python3.6/site-packages/hkube_python_wrapper/codeApi/hkube_api.py", line 25, in algorithmExecutionDone
    result = self._dataAdapter.tryGetDataFromPeerOrStorage(response)
  File "/home/tamirre/envs/python36/lib/python3.6/site-packages/hkube_python_wrapper/wrapper/data_adapter.py", line 124, in tryGetDataFromPeerOrStorage
    dataPath = options.get('path')
AttributeError: 'int' object has no attribute 'get'
2020-06-25T13:57:01Z <Greenlet at 0x7f87d87a0548: <bound method WebsocketClient.algorithmExecutionDone of <hkube_python_wrapper.wrapper.wc.WebsocketClient object at 0x7f87f1d27978>>({'execId': '1', 'response': 1})> failed with AttributeError

**Comment by tamir321** [comment]
tested on  "systemVersion": "v1.3.58",
    "fullSystemVersion": "v1.3.58-1593434450223",

hkube-python-wrapper 2.0.4
